[package]
name = "maf_task_dispatcher"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
maf_runtime_store = { path = "../maf_runtime_store" }
serde.workspace = true
